services:
  backend:
    image: backend-processor
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 8081

  frontend:
    image: frontend
    build:
      context: ../file-magic-processor
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:80"
    environment:
      - BACKEND_URL=http://backend:8081